ptfinder/ptfinder/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from ptfinderApp import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from ptfinderApp.views import search

urlpatterns = [
    path('', views.index, name='index'),
    path('ptfinder/', include('ptfinderApp.urls', namespace="ptfinderApp")),
    path('admin/', admin.site.urls),
    path('login/', views.user_login, name='login'),
    url(r'^results/$', search, name="search"),
    path('register/', views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ptfinder/ptfinderApp/urls.py
from django.urls import path
from ptfinderApp import views

from ptfinderApp.views import search
from django.conf.urls import url

from django.urls import re_path
app_name = 'ptfinder'


urlpatterns = [
    path('', views.index, name="index"),
    path('user/', views.user, name='user'),
     url(r'^results/$', search, name="search"),
    path('user/login/', views.login , name='login'),
    path('user/register/', views.register , name='register'),
    path('user/register/trainer', views.trainer_register , name='trainer_register'),
    re_path(r'^user/(?P<username>.*)/edit_profile/$', views.edit_profile , name='edit_profile'),
    re_path(r'^user/(?P<username>.*)/$', views.user_profile , name='user_profile'),
    path('trainer/', views.trainer , name='trainer'),
    re_path(r'^trainer/(?P<account>.*)/$', views.trainer_profile , name='trainer_profile'), 
    path('book/', views.book , name='book'),
    re_path(r'^book/(?P<account>.*)/create_booking/$', views.create_booking, name='create_booking'),
    re_path(r'^book/(?P<uservar>.*)/$', views.view_bookings , name='view_bookings'),
    path('contact_us/', views.contact_us , name='contact_us'),
    path('gym/', views.gym , name='gym'), 
    re_path(r'^gym/(?P<name>.*)/$', views.gym_profile , name='gym_profile'), 
]

ptfinder/ptfinderApp/forms.py
from PIL import Image
from django import forms
from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from ptfinderApp.models import UserProfile, Trainer, Booking, Gym
import datetime


class UserForm(forms.ModelForm):
        
    username = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}), required=True)
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bob'}), required=True)
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ross'}), required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'aria-describedby': 'userPassHelp'}), required=True)
        
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password',)
            
class UserProfileForm(UserForm):
    conPass = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
    experience = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'e.g. None, 1 Year etc.', 'aria-required': 'false', 'rows':'3', 'cols': '3'}))    
    location = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Glasgow', 'aria-describedby': 'userLocationHelp'}))
    sex = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sex'}))
    img = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file', 'accept': '.jpg, .jpeg, .png, image/jpeg, image/png', 'aria-required': 'false'}), required=False)
    
    class Meta:
        model = UserProfile
        fields = ('experience','sex','location','img',)
        
class TrainerProfileForm(UserForm):
    conPass = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
    sex = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sex'}))
    img = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file', 'accept': '.jpg, .jpeg, .png, image/jpeg, image/png', 'aria-required': 'false'}))
    contact_no = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+44 7123 456 789'}))
    specialism = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'e.g. None, 1 Year etc.', 'aria-required': 'false', 'rows':'3', 'cols': '3'}))
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Hourly/Session Charge'}))
    
    gyms = Gym.objects.all()
    gym_data = [(gym.g_id, gym.name) for gym in gyms]
    g_id = forms.ChoiceField(choices=gym_data, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Trainer 
        fields = ('g_id','contact_no','specialism','sex','img','price',)
        
class CreateBookingForm(forms.ModelForm):
    datetime = forms.DateTimeField(help_text="[yyyy-mm-dd HH:MM]", initial=datetime.datetime.now())
    
    class Meta:
        model = Booking
        fields = ('username','trainer_username', 'datetime', 'location',)

ptfinder/ptfinderApp/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import render, redirect
from django.db.models import Q

from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views import View
from ptfinderApp.forms import UserForm, UserProfileForm, TrainerProfileForm, CreateBookingForm
from ptfinderApp.models import UserProfile, Booking, Gym, Trainer

def index(request):
    context_dict = {}

    return render(request, 'ptfinderApp/index.html', context=context_dict)

def user(request):
    context_dict = {}


    return render(request, 'ptfinderApp/profile.html', context=context_dict)
  
def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:

                login(request, user)
                return redirect(reverse('ptfinder:index'))
            else:

                return HttpResponse("Your PTfinder account is disabled.")
        else:
    
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:

        return render(request, 'ptfinderApp/login.html')

def search(request):
    template = 'ptfinderApp/index.html'

    query = request.GET.get('q')

    submitbutton= request.GET.get('submit')
    firstname= Trainer.t_account.first_name

    results = Trainer.objects.filter(Q(firstname__icontains=query) | Q(sex__icontains=query))

    context = {
        'results': results,
        'submitbutton': submitbutton,
        }
    return render(request, template, context)

   # return render(request, 'ptfinderApp/user.html', context=context_dict)

def user_profile(request):
    context_dict = {}

    return render(request, 'ptfinderApp/user-profile.html', context=context_dict)

def register(request):
    context_dict = {}
    
    registered = False
    if request.method == 'POST':
        userForm = UserForm(request.POST)
        userProfileForm = UserProfileForm(request.POST)

        print(userForm.is_valid())
        print(userProfileForm.is_valid())

        if userForm.is_valid() and userProfileForm.is_valid():
            user = userForm.save()
            if user.cleaned_data['password'] == user.cleaned_data['conpass']:
                user.set_password(user.password)
                user.save()

            userProfile = userProfileForm.save(commit=False)
            userProfile.account = user

            if 'img' in request.FILES:
                userProfile.img = request.FILES['img']

            userProfile.save()
            registered = True
        else:
            print(userForm.errors, userProfileForm.errors)
    else:
        userForm = UserForm()
        userProfileForm = TrainerProfileForm()

    context_dict = {'base_user_form': userForm, 'user_form': userProfileForm, 'registered': registered}

    return render(request, 'ptfinderApp/register.html', context=context_dict)

def trainer_register(request):
    registered = False
    if request.method == 'POST':
        base_user_form = UserForm(request.POST)
        trainer_form = TrainerProfileForm(request.POST)
        
        if base_user_form.is_valid() and trainer_form.is_valid():
            user = base_user_form.save()
            user.set_password(user.password)
            user.save()
            trainer = trainer_form.save(commit=False)
            trainer.t_account = user
            
            if 'picture' in request.FILES:
                trainer.picture = request.FILES['picture']
                
            trainer.save()
            registered = True
        else:
            print(base_user_form.errors, trainer_form.errors)
    else:
        base_user_form = UserForm()
        trainer_form = TrainerProfileForm()
    
    context_dict = {'base_user_form': base_user_form, 'trainer_form': trainer_form,'registered':registered}

    return render(request, 'ptfinderApp/register-trainer.html', context=context_dict)

@login_required
def edit_profile(request, username):
    userprofile = UserProfile.objects.get_or_create(account=request.user)[0]
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST,instance=userprofile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            custom_form = profile_form.save(commit=False)
            custom_form.user = user_form
            custom_form.save()
            return redirect('ptfinder:user')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
            
    context_dict = {'user_form':user_form, 'profile_form':profile_form}

    return render(request, 'ptfinderApp/edit-profile.html', context=context_dict)
    
def gym(request):
#name, owner, city, address_postcode
    context_dict = {}
    
    if request.method == 'POST':
        
        search = request.POST.get('search')
        
        try:
            gyms = Gym.objects.get(name=search)
            if gyms:
                context_dict['gyms'] = gyms
                context_dict['search_type'] = "specific"
                print(context_dict)
                return render(request, 'ptfinderApp/gym.html', context=context_dict)
        except:
            pass
        
        
        try:
            gyms = Gym.objects.filter(owner=search)
            if gyms:
                context_dict['gyms'] = gyms
                context_dict['search_type'] = "generic"
                return render(request, 'ptfinderApp/gym.html', context=context_dict)
        except:
            pass
            
        
        gyms = Gym.objects.filter(address_postcode=search)
        if gyms:
            context_dict['gyms'] = gyms
            context_dict['search_type'] = "generic"
            return render(request, 'ptfinderApp/gym.html', context=context_dict)        
            
        gyms = Gym.objects.filter(city=search) 
        if gyms:
            context_dict['gyms'] = gyms
            context_dict['search_type'] = "generic"
            return render(request, 'ptfinderApp/gym.html', context=context_dict)
        
        return render(request, 'ptfinderApp/gym.html', context=context_dict)
       
    else:
        gyms = Gym.objects.order_by('-name')[:5]
        context_dict['gyms'] = gyms 
        context_dict['search_type'] = "generic"
        return render(request, 'ptfinderApp/gym.html', context=context_dict)
        

def gym_profile(request):
    context_dict = {}

    return render(request, 'ptfinderApp/gym-profile.html', context=context_dict)
    
def contact_us(request):
    context_dict = {}
    
    return render(request, 'ptfinderApp/contact_us.html', context=context_dict)

def book(request):
    context_dict = {}

    return render(request, 'ptfinderApp/book.html', context=context_dict)

@login_required
def create_booking(request, account):
    user_profile = UserProfile.objects.get_or_create(account=request.user)[0]
    
    if request.method == 'POST':
        booking_form = CreateBookingForm(request.POST)
        
        if booking_form.is_valid():
            booking = booking_form.save(commit=False)
            booking.username = user_profile
            booking.save()
            return redirect('ptfinder:index')
        else:
            print(booking_form.errors)
    else:
        booking_form = CreateBookingForm()
    
    context_dict = {'booking_form':booking_form}
    
    return render(request, 'ptfinderApp/create-booking.html', context=context_dict)

@login_required
def view_bookings(request, uservar):
    context_dict = {}
    
    bookings = Booking.objects.filter(username__account__username=uservar)
    if bookings:
       pass
    else:
        bookings = Booking.objects.filter(t_username__t_account__username=uservar)
  
            
    
    context_dict['bookings'] = bookings
        
    #context_dict
    

    return render(request, 'ptfinderApp/view-bookings.html', context=context_dict)
    
def trainer(request):
    context_dict = {'trainer_list': get_trainer_list()}
    
    if request.method == 'POST':
        search = request.POST.get('search')
        
        try:
            trainers = Trainer.objects.all()
            
            for trainer in trainers:
                if trainer.t_account.username == search:
                    output_trainer = trainer
                    
            if output_trainer:
                context_dict['trainer'] = output_trainer
                print(context_dict)
        except Exception as e:
            print("except")
            print(e)
            pass
    
    return render(request, 'ptfinderApp/trainer.html', context=context_dict)

def get_trainer_list(start_results=0,end_results=0):
    trainer_list = {}
    # You may find this helpful: https://docs.djangoproject.com/en/3.0/ref/models/querysets/

    if end_results == 0:
        pass

    return trainer_list

def trainer_profile(request):
    context_dict = {}

    return render(request, 'ptfinderApp/trainer-profile.html', context=context_dict)

ptfinder/templates/ptfinderApp/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta description="Join millions of users and train today.">
        {% block meta_block %}
        {% endblock %}
        <title>PTFinder - 
            {% block title_block %}
                Train With Us
            {% endblock %}
		</title>
		<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'ptfinder/css/main.css' %}">
            <style>
          body {
    background-image:linear-gradient(-135deg, #372185 25%,#520b0f 100%);
    background-size: cover;
    background-repeat: no-repeat;
    width: 100%;
  height: 160vh;
    
  }

main {
    width: 90vw;
    margin: 0 auto;
    padding: 30px 20px;
    min-height: calc(100vh - 50px); 
}
footer {
  width: 100%;
  height: 60px;
  flex-shrink: 0;
  background-color: #134c7d;
 
}
    .button {
  background-color: transparent;
  border-radius: 30px;
  border: none;
  color: white;
  padding: 7px 24px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 6px 2px;
  cursor: pointer;
  border: 2px solid white;
  position: absolute;
  right: 50px;
}
.button:hover {
  text-decoration: none;
  background-color: white;
  border-color: white;
  color: black;
}
.navbar-fixed-top {
background: transparent;
}

.navbar-fixed-top.scrolled {
  background-color:#0e1f36;
  color: black;
}
            </style>   
    </head>


    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
                <a class="navbar-brand" href="{% url 'ptfinder:index' %}"><img src="{% static 'ptfinder/images/PTfinder_logo2.png'%}" alt="logo" width = "40" height = "50"/> </a>
                <a class="navbar-brand" href="{% url 'ptfinder:index' %}">PTfinder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ptfinder:gym' %}">Gyms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ptfinder:trainer' %}">Trainers</a>
                        </li>
                        
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ptfinder:user' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ptfinder:view_bookings' %}}">My Bookings</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ptfinder:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ptfinder:register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
      
        <main style="flex: 1">
            <div class="container-fluid">
                {% block body_block %}
                {% endblock %}
            </div>
        </main>
        <footer class="text-center bg-dark text-white mt-4">
            <div class="container-fluid py-3">
                Copyright 2020 | PTFinder
            </div> 
        </footer>
        <script>
            $(window).scroll(function(){
            $('nav').toggleClass('scrolled', $(this).scrollTop() > 200);
            });
           </script>
    </body>
</html>

ptfinder/templates/ptfinderApp/book.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block title_block %}
{% endblock %}

{% block body_block %}           
{% endblock %}

ptfinder/templates/ptfinderApp/contact_us.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block title_block %}
Contact Us
{% endblock %}

{% block body_block %}
<h1> Contact us at any of the following </h1>
General Enquiries: Enquiries@ptfinder.co.uk <br>
Call us on 01543 643 543 <br>
Follow us on Facebook at www.Facebook.com/ptfinder <br>
or follow our Twitter @ptfinderofficial <br> </br>


<h3> Meet the Team! </h3>
<b> Glen: </b> <br>
e-mail: Glen@ptfinder.co.uk <br>
twitter: @GlenRocks123 <br> </br> 

<b> Lewis: </b> <br>
e-mail: Lewis@ptfinder.co.uk <br>
twitter: @LewisIzCool <br> </br> 

<b> Cameron: </b> <br>
e-mail: Cammy@ptfinder.co.uk <br>
twitter: @Xx_CAMMY_xX <br> </br> 

<b> Joumana: </b> <br>
e-mail: Joumana@ptfinder.co.uk <br>
twitter: @Joumana_anamuoJ <br> </br> 

<b> Kieren: </b> <br>
e-mail: Kieren@ptfinder.co.uk <br>
twitter: @KierenKK99 <br> </br> 
{% endblock %}

ptfinder/templates/ptfinderApp/create-booking.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block title_block %}
    Book A Session
{% endblock %}

{% block body_block %}
    <h1> Book a Training Session </h1>
    Fill out the form below and click submit to book your session <br />
	Choose the username for your chosen trainer, alter the date and time for your session and say which city you'd like your session in. <br />
	<br />
    <form id="create-booking" method="post" action="{% url 'ptfinder:create_booking' account %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ booking_form.as_p }}
        <input name="Submit" type="submit" value="Confirm Booking" />
    </form>
     
{% endblock %}

ptfinder/templates/ptfinderApp/edit-profile.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block title_block %}
	Update Profile
{% endblock %}

{% block body_block %}
<form id="edit-profile" method="post" action="{% url 'ptfinder:edit_profile' username %}"enctype="multipart/form-data">
	{% csrf_token %}
	{{ user_form.as_p }}
	{{ profile_form.as_p }}
	<input type="submit" name="editProfile" value="Confirm changes" />
</form>
{% endblock %}

ptfinder/templates/ptfinderApp/gym.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block title_block %}
Gym
{% endblock %}

{% block body_block %}
<h1> Search for gyms! </h1>
<form id="gym_search" method="post" action="{% url 'ptfinder:gym' %}">
	{% csrf_token %}

	search: <input type="text" name="search" value="" size="50" />
	<br />
	
	{% if gyms %}
		{% if search_type == "specific" %} 
			Gym Name: {{ gyms.name }} <br>
			Gym Owner: {{ gyms.owner }} <br>
			Gym Address: {{ gyms.addressline1 }} <br>
			{{ gyms.addressline2 }} <br>
			{{ gyms.address_postcode }} <br>
			Gym City: {{ gyms.city }} <br>
			gym Description: {{ gyms.description }} <br>
			<div>
            			<img src="{% static " ptfinder/media/gym_images/{{ gyms.name }}.jpg" %}" alt="Oops! it appears this gym doesnt have a picture" width=600 />
           		</div>

		{% else %}
			<ul>
			{% for gym in gyms %}
				<li> 
					{{ gym.name }}
				</li>
			{% endfor %}
			</ul>
		{% endif %}
	{% else %}
		<strong> couldnt find any for ya chief, change the search and give her another spin! </strong>
	{% endif %}
{% endblock %}

ptfinder/templates/ptfinderApp/register-trainer.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block meta_block %}
    {% if registered %}
        <meta http-equiv="refresh" content="5" url="{% url 'ptfinder:index' %}">
    {% endif %}
{% endblock %}

{% block title_block %}
	Register
{% endblock %}

{% block body_block %}
{% if registered %}
    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Thank you for Registering!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body py-3">
                    Return to the <a href="{% url 'ptfinder:index' %}">Homepage</a> or go to your <a href="">Profile</a>
                </div>
            </div>
        </div>
    </div>
{% else %}
<div class="card bg-light w-50 mt-4 mx-auto">
    <div class="card-body w-75 mx-auto">
        <h4 class="card-title mt-3 text-center">Trainer Registration</h4>
        <p class="text-center text-muted">Access More Trainees Than Ever Before</p>
        <form id="trainer_form" method="post" action="{% url 'ptfinder:trainer_register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% if base_user_form.errors %}
                {% for field in base_user_form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            {% if trainer_form.errors %}
                {% for field in trainer_form %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                <label for="username">Username:</label>
                {{ base_user_form.username }}
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-12 col-md-6">
                        <label for="first_name">Firstname:</label>
                        {{ base_user_form.first_name }}
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="last_name">Surname:</label>
                        {{ base_user_form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-12 col-md-6">
                        <label for="password">Password:</label>
                        {{ base_user_form.password }}
                        <small id="trainerPassHelp" class="form-text text-muted">Please use a strong password. <a href="https://www.ncsc.gov.uk/blog-post/three-random-words-or-thinkrandom-0">What is a strong password?</a></small>
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="conPass">Confirm Password:</label>
                        {{ trainer_form.conPass }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-12 col-md-6">
                        <label for="contact_no">Contact No:</label>
                        {{ trainer_form.contact_no }}
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="price">Price:</label>
                        {{ trainer_form.price }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="specialism">Specialism:</label>
                {{ trainer_form.specialism }}
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-12 col-md-4">
                        <label for="sex">Sex:</label>
                        {{ trainer_form.sex }}
                    </div>
                    <div class="col-12 col-md-8">
                        <label for="g_id">Gym:</label>
                        {{ trainer_form.g_id }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="img">Profile Picture:</label>
                {{ trainer_form.img }}
            </div>
            <div class="form-check" >
                <input type="checkbox" class="form-check-input" id="privacy-check">
                <label class="form-check-label small" for="privacy-check">I have read and understood the <a href=#>Privacy and GDPR Policy</a>.</label>
            </div>
            <br />
            <div class="form-group">
                <div class="form-row justify-content-center">
                    <div class="col-4">
                        <input type="submit" class="btn btn-block btn-dark mb-2" value="Register">
                    </div>
                </div>
                <br />
                <div class="form-row">
                    <div class="col text-center">
                        Already a member? <a href="{% url 'ptfinder:login' %}">Login</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endif %}
<script>
    $(window).on('load',function(){
        $('#registration-modal').modal('show');
    });
</script>
{% endblock %}

ptfinder/templates/ptfinderApp/view-bookings.html
{% extends 'ptfinderApp/base.html' %}
{% load static %}

{% block title_block %}
    Bookings
{% endblock %}

{% block body_block %}       
    <div class="container-fluid">
        <div class="row centre-content">
            <div class="col">
                <h2><u>Your Bookings</u></h2>
                    {% for booking in bookings %}<hr><br>
                        Trainer name: {{ booking.t_username.getName }}<br>
                        Trainer username: <a href="{% url 'ptfinderApp:trainer_profile' booking.t_username %}">{{ booking.t_username }}</a><br>
                        Date: {{ booking.datetime }}<br>
                        Location: {{ booking.location}}
                        <br>
                        <hr>
                    {% endfor %}
            </div>
        </div>
    </div>
    
{% endblock %}